# Generated by Django 3.2.2 on 2021-05-10 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner_name', models.CharField(max_length=300)),
                ('allowed_mac_addresses', models.CharField(max_length=2000)),
                ('max_access_limit', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('activation_date', models.DateTimeField(null=True)),
                ('life_span', models.IntegerField(default=1)),
            ],
        ),
    ]
