# Generated by Django 3.2.2 on 2021-05-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='owner_name',
            new_name='client_name',
        ),
    ]
