# Generated by Django 3.2.2 on 2021-05-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0002_rename_owner_name_license_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='activation_date',
            field=models.DateTimeField(blank=True, help_text='optional, activation date', null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='allowed_mac_addresses',
            field=models.CharField(help_text='mac addresses, comma separated', max_length=2000),
        ),
        migrations.AlterField(
            model_name='license',
            name='client_name',
            field=models.CharField(help_text="Client's or owner name", max_length=300),
        ),
        migrations.AlterField(
            model_name='license',
            name='life_span',
            field=models.IntegerField(default=1, help_text='period in days that the license is valid'),
        ),
        migrations.AlterField(
            model_name='license',
            name='max_access_limit',
            field=models.IntegerField(default=1, help_text='max no. of users allowed'),
        ),
    ]
