# Generated by Django 3.2.2 on 2021-05-11 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0003_auto_20210510_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_secret_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
