# Generated by Django 3.2.2 on 2021-05-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0004_license_license_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='allowed_mac_addresses',
        ),
        migrations.AddField(
            model_name='license',
            name='license_type',
            field=models.CharField(choices=[('Named', 'Named')], default='Named', max_length=25),
        ),
    ]
