# Generated by Django 3.2.2 on 2021-05-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0005_auto_20210517_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.CharField(choices=[('Named', 'Named')], max_length=25),
        ),
    ]
