# Generated by Django 3.2.2 on 2021-05-21 09:43

from django.db import migrations, models
import license_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0006_alter_license_license_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_key',
            field=models.TextField(default=license_management.models.generate_key, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.CharField(choices=[('Concurrent', 'Concurrent'), ('Named', 'Named')], max_length=25),
        ),
    ]
