# Generated by Django 3.2.2 on 2021-06-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0007_auto_20210521_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
