# Generated by Django 3.2.2 on 2021-07-29 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('license_management', '0008_license_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='client_name',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('public_key', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='license',
            name='client',
            field=models.ForeignKey(help_text='License owner', null=True, on_delete=django.db.models.deletion.CASCADE, to='license_management.client'),
        ),
    ]
