# Generated by Django 3.2.2 on 2021-08-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0010_auto_20210729_1738'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='Client and public key constraint',
        ),
        migrations.AddField(
            model_name='client',
            name='private_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='license',
            name='license_key',
            field=models.TextField(editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('public_key', 'private_key', 'name'), name='Client and public key constraint'),
        ),
    ]
